// <auto-generated />
using System;
using Internalexamportal.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Internalexamportal.DataAccessLayer.Migrations
{
    [DbContext(typeof(InternalExamportalContext))]
    [Migration("20200710062511_Added_New_Test_Settings_Lookup")]
    partial class Added_New_Test_Settings_Lookup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.AccessCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessTestCode");

                    b.Property<int>("ActivationCodeId");

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.HasIndex("ActivationCodeId")
                        .IsUnique();

                    b.ToTable("AccessCode");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.ActivationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivationTypeId");

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("ActivationTypeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TestId");

                    b.ToTable("ActivationCode");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.ActivationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ActivationType");

                    b.HasData(
                        new { Id = 1, Type = "CommonType" },
                        new { Id = 2, Type = "AccessType" }
                    );
                });

            modelBuilder.Entity("Internalexamportal.DataAccessLayer.Entities.ApplicationError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exception");

                    b.Property<string>("Message");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("ApplicationError");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CandidateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("CandidateGroup");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CommonCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivationCodeId");

                    b.Property<string>("CommonTestCode");

                    b.HasKey("Id");

                    b.HasIndex("ActivationCodeId")
                        .IsUnique();

                    b.ToTable("CommonCode");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CompletedTestDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionId");

                    b.Property<int>("QuestionOptionId");

                    b.Property<int>("SubmittedTestId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionOptionId");

                    b.HasIndex("SubmittedTestId");

                    b.ToTable("CompletedTestDetails");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CorrectOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Option");

                    b.HasKey("Id");

                    b.ToTable("CorrectOption");

                    b.HasData(
                        new { Id = 1, Option = "A" },
                        new { Id = 2, Option = "B" },
                        new { Id = 3, Option = "C" },
                        new { Id = 4, Option = "D" },
                        new { Id = 5, Option = "true" },
                        new { Id = 6, Option = "false" },
                        new { Id = 7, Option = "subjective" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.DifficultLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.ToTable("DifficultLevel");

                    b.HasData(
                        new { Id = 1, Level = "Difficult" },
                        new { Id = 2, Level = "Easy" },
                        new { Id = 3, Level = "Normal" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Group");

                    b.HasData(
                        new { Id = 1, Name = "General" },
                        new { Id = 2, Name = "Others" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<int>("ParentId");

                    b.Property<string>("PermissionName");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new { Id = 1, Description = "", IsActive = true, ParentId = 0, PermissionName = "Dashboard" },
                        new { Id = 2, Description = "", IsActive = true, ParentId = 0, PermissionName = "Question Manager" },
                        new { Id = 3, Description = "", IsActive = true, ParentId = 0, PermissionName = "Subject Manager" },
                        new { Id = 4, Description = "", IsActive = true, ParentId = 0, PermissionName = "Test Manager" },
                        new { Id = 5, Description = "", IsActive = true, ParentId = 0, PermissionName = "Candidates Manager" },
                        new { Id = 6, Description = "", IsActive = true, ParentId = 0, PermissionName = "Admin Manager" },
                        new { Id = 7, Description = "", IsActive = true, ParentId = 1, PermissionName = "View" },
                        new { Id = 8, Description = "", IsActive = true, ParentId = 1, PermissionName = "Add" },
                        new { Id = 9, Description = "", IsActive = true, ParentId = 2, PermissionName = "View" },
                        new { Id = 10, Description = "", IsActive = true, ParentId = 2, PermissionName = "Add/Edit" },
                        new { Id = 11, Description = "", IsActive = true, ParentId = 2, PermissionName = "Delete" },
                        new { Id = 12, Description = "", IsActive = true, ParentId = 2, PermissionName = "Import" },
                        new { Id = 13, Description = "", IsActive = true, ParentId = 3, PermissionName = "View" },
                        new { Id = 14, Description = "", IsActive = true, ParentId = 3, PermissionName = "Add/Edit" },
                        new { Id = 15, Description = "", IsActive = true, ParentId = 3, PermissionName = "Delete" },
                        new { Id = 16, Description = "", IsActive = true, ParentId = 4, PermissionName = "View" },
                        new { Id = 17, Description = "", IsActive = true, ParentId = 4, PermissionName = "Add/Edit" },
                        new { Id = 18, Description = "", IsActive = true, ParentId = 4, PermissionName = "Delete" },
                        new { Id = 19, Description = "", IsActive = true, ParentId = 5, PermissionName = "View" },
                        new { Id = 20, Description = "", IsActive = true, ParentId = 5, PermissionName = "Add/Edit" },
                        new { Id = 21, Description = "", IsActive = true, ParentId = 5, PermissionName = "Delete" },
                        new { Id = 22, Description = "", IsActive = true, ParentId = 5, PermissionName = "Import" },
                        new { Id = 23, Description = "", IsActive = true, ParentId = 6, PermissionName = "View" },
                        new { Id = 24, Description = "", IsActive = true, ParentId = 6, PermissionName = "Add/Edit" },
                        new { Id = 25, Description = "", IsActive = true, ParentId = 6, PermissionName = "Delete" },
                        new { Id = 26, Description = "", IsActive = true, ParentId = 6, PermissionName = "Role Permissions" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionTypeId");

                    b.Property<int>("SubjectId");

                    b.Property<int>("SubjectTopicId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectTopicId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionId");

                    b.Property<int>("QuestionOptionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("QuestionAnswer");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("DifficultLevel");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("NegativeMark");

                    b.Property<int>("QuestionId");

                    b.Property<string>("RightMark");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("QuestionMark");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsAnswer");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("OptionText");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOption");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("QuestionType");

                    b.HasData(
                        new { Id = 1, Type = "Multiple Choice Question" },
                        new { Id = 2, Type = "True/False" },
                        new { Id = 3, Type = "Subjective" }
                    );
                });

            modelBuilder.Entity("Internalexamportal.DataAccessLayer.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");

                    b.HasData(
                        new { Id = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6", ConcurrencyStamp = "03f9632b-47fd-4ec4-a53f-39e14666d282", CreatedDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), IsActive = true, Name = "SuperAdmin", NormalizedName = "SUPERADMIN" },
                        new { Id = "859e583d-691f-40b4-adb2-828703ee1dd7", ConcurrencyStamp = "31a59558-0a25-48f4-91ba-6a2ffc0ad41c", CreatedDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), IsActive = true, Name = "Admin", NormalizedName = "ADMIN" },
                        new { Id = "15bda09a-effe-4634-88dc-855d9642bfed", ConcurrencyStamp = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6", CreatedDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), IsActive = true, Name = "Candidate", NormalizedName = "CANDIDATE" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId");

                    b.Property<string>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new { Id = 1, PermissionId = 1, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 2, PermissionId = 2, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 3, PermissionId = 3, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 4, PermissionId = 4, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 5, PermissionId = 5, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 6, PermissionId = 6, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 7, PermissionId = 7, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 8, PermissionId = 8, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 9, PermissionId = 9, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 10, PermissionId = 10, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 11, PermissionId = 11, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 12, PermissionId = 12, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 13, PermissionId = 13, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 14, PermissionId = 14, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 15, PermissionId = 15, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 16, PermissionId = 16, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 17, PermissionId = 17, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 18, PermissionId = 18, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 19, PermissionId = 19, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 20, PermissionId = 20, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 21, PermissionId = 21, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 22, PermissionId = 22, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 23, PermissionId = 23, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 24, PermissionId = 24, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 25, PermissionId = 25, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 47, PermissionId = 26, RoleId = "a7ffd1c1-c7ee-4ddc-a10e-882dcba329c6" },
                        new { Id = 26, PermissionId = 1, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 27, PermissionId = 2, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 28, PermissionId = 3, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 29, PermissionId = 4, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 30, PermissionId = 5, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 31, PermissionId = 7, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 32, PermissionId = 8, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 33, PermissionId = 9, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 34, PermissionId = 10, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 35, PermissionId = 11, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 36, PermissionId = 12, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 37, PermissionId = 13, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 38, PermissionId = 14, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 39, PermissionId = 15, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 40, PermissionId = 16, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 41, PermissionId = 17, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 42, PermissionId = 18, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 43, PermissionId = 19, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 44, PermissionId = 20, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 45, PermissionId = 21, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" },
                        new { Id = 46, PermissionId = 22, RoleId = "859e583d-691f-40b4-adb2-828703ee1dd7" }
                    );
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSettingApplied");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("TestId");

                    b.Property<int>("TestSettingTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TestId");

                    b.HasIndex("TestSettingTypeId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubjectTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("SubjectId");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectTopic");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubmittedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionId");

                    b.Property<int>("QuestionOptionId");

                    b.Property<int>("TestId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionOptionId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("SubmittedOption");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubmittedTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttemptedQuestion");

                    b.Property<int>("CorrectQuestion");

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("InCorrectQuestion");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MaximumMark");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("NegativeMark");

                    b.Property<int>("ReviewedQuestion");

                    b.Property<int>("RightMark");

                    b.Property<int>("SkippedQuestion");

                    b.Property<DateTime>("SubmitDate");

                    b.Property<int>("TestId");

                    b.Property<string>("TimeTaken");

                    b.Property<int>("TotalMark");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("SubmittedTest");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("DifficultLevelId");

                    b.Property<double>("Duration");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionTypeId");

                    b.Property<int>("TestInstructionId");

                    b.Property<string>("TestName");

                    b.Property<int>("TotalMark");

                    b.Property<int>("TotalQuestion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DifficultLevelId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("TestInstructionId");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Instruction");

                    b.Property<string>("InstructionDescripiton");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TestInstruction");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestPublish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime?>("EndDate");

                    b.Property<double>("EndTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime?>("StartDate");

                    b.Property<double>("StartTime");

                    b.Property<int>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("TestPublish");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("QuestionId");

                    b.Property<int>("TestId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("TestQuestion");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("SettingId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("SettingId");

                    b.ToTable("TestSetting");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("TestSettingType");

                    b.HasData(
                        new { Id = 1, Type = "Shuffling" },
                        new { Id = 2, Type = "Display Result" },
                        new { Id = 3, Type = "Multiple Attempt" },
                        new { Id = 4, Type = "Window Minimise Warning" }
                    );
                });

            modelBuilder.Entity("Internalexamportal.DataAccessLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.UserPersonalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreatedById");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("State");

                    b.Property<string>("UserId");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserPersonalDetail");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.AccessCode", b =>
                {
                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.ActivationCode", "ActivationCode")
                        .WithOne("AccessCode")
                        .HasForeignKey("InternalExamportal.DataAccessLayer.Entities.AccessCode", "ActivationCodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.ActivationCode", b =>
                {
                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.ActivationType", "ActivationType")
                        .WithMany()
                        .HasForeignKey("ActivationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithMany("ActivationCode")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CandidateGroup", b =>
                {
                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User", "User")
                        .WithMany("CandidateGroup")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CommonCode", b =>
                {
                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.ActivationCode", "ActivationCode")
                        .WithOne("CommonCode")
                        .HasForeignKey("InternalExamportal.DataAccessLayer.Entities.CommonCode", "ActivationCodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.CompletedTestDetails", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.SubmittedTest", "SubmittedTest")
                        .WithMany()
                        .HasForeignKey("SubmittedTestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Question", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.SubjectTopic", "SubjectTopic")
                        .WithMany()
                        .HasForeignKey("SubjectTopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithOne("QuestionAnswer")
                        .HasForeignKey("InternalExamportal.DataAccessLayer.Entities.QuestionAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionMark", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithOne("QuestionMark")
                        .HasForeignKey("InternalExamportal.DataAccessLayer.Entities.QuestionMark", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.QuestionOption", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithMany("QuestionOption")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.RolePermission", b =>
                {
                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Setting", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithMany("Setting")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.TestSettingType", "TestSettingType")
                        .WithMany()
                        .HasForeignKey("TestSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Subject", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubjectTopic", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("SubjectTopic")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubmittedOption", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.SubmittedTest", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithMany("SubmittedTest")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.Test", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.DifficultLevel", "DifficultLevel")
                        .WithMany()
                        .HasForeignKey("DifficultLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.TestInstruction", "TestInstruction")
                        .WithMany()
                        .HasForeignKey("TestInstructionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestInstruction", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestPublish", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithOne("TestPublish")
                        .HasForeignKey("InternalExamportal.DataAccessLayer.Entities.TestPublish", "TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestQuestion", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Question", "Question")
                        .WithMany("TestQuestion")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Test", "Test")
                        .WithMany("TestQuestion")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.TestSetting", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalExamportal.DataAccessLayer.Entities.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InternalExamportal.DataAccessLayer.Entities.UserPersonalDetail", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Internalexamportal.DataAccessLayer.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
