using Internalexamportal.DataAccessLayer.Entities;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;

namespace Internalexamportal.Core.Services
{
    public class VerificationCodeService : IVerificationCodeService
    {
        private readonly UserManager<User> _userManager;
        public VerificationCodeService(
            UserManager<User> userManager
            )
        {
            _userManager = userManager; 
        }
        public async Task<string> GenerateVerificationCode(User user) {

            //Return Code. Code is generated by identity itself. 
           return await _userManager.GenerateTwoFactorTokenAsync(user, "Phone");
        }

        //Generate Cryptogrphically Secure Randoom Number
        //private string GetRandomNumber(int len)
        //{
        //    int maxSize = len;
        //    char[] chars = new char[30];
        //    string a;
        //    a = "1234567890";
        //    chars = a.ToCharArray();
        //    int size = maxSize;
        //    byte[] data = new byte[1];
        //    RNGCryptoServiceProvider crypto = new RNGCryptoServiceProvider();
        //    crypto.GetNonZeroBytes(data);
        //    size = maxSize;
        //    data = new byte[size];
        //    crypto.GetNonZeroBytes(data);
        //    StringBuilder result = new StringBuilder(size);
        //    foreach (byte b in data) { result.Append(chars[b % (chars.Length)]); }
        //    return result.ToString();
        //}
    }
}
